service: aws-nodejs
plugins:
  - serverless-dotenv-plugin
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-west-2
  profile: hackathon

functions:
  main:
    handler: handler.main
    events:
      - http:
          path: corporate-actions
          method: get
          cors: true
